environmentConfig:
  envName: dev
  cluster: "https://kubernetes.default.svc"
  namespace: apps
  keyVaulName: "kv-dev-northeurope-sndbx"
  keyVaultUrl: "https://kv-dev-northeurope-sndbx.vault.azure.net/"
  managedIdClientId: "e7b78204-65c8-4961-be4e-44c6834f91fe"
  resourceGroup: "rg-dev-northeurope-sndbx"
  subscriptionId: "c293e084-4429-40d1-a197-c69c22ffadc1"
  postgresDbHost: "psql-dev-northeurope-sndbx.postgres.database.azure.com"
  postgresDbPort: "5432"
  secretFingerprint: "SNDBXDEV"
  kafkaHost: "pkc-lz6r3.northeurope.azure.confluent.cloud:9092"
  couchbaseHost: "couchbases://cb.nuyollpiedhmc8.cloud.couchbase.com"
  timeZone: "Europe/London"
  tokenIssuer: "https://api.sndbx.dev.transcendplatform.com/issue-token/token"
  envUrl: "https://sndbx.dev.transcendplatform.com"
  apiUrl: "https://api.sndbx.dev.transcendplatform.com"
  clients:
    cardPin: eb98
    clientCredentialsService: d382
    employeeService: 77c7
    fpsQueryTool: 98d1
    fpsStoreConfig: c02c
    fulfilmentOrderProcessor: 6e78
    fulfilmentOrderProcessorGroupingCronJob: 3f76
    fulfilmentOrderProcessorSchedulerCronJob: 44fc
    gravity: c650
    issueTokenService: 5687
    labelPrintingService: 4ad3
    loadingService: d3c9
    logisticUnitService: c793
    luTileGridSyncCronJob: 3e74
    operationsDataService: 963b
    orderAdapter: 13f1
    pickAdmin: e80a
    pickingApp: fcad
    pickingService: cd75
    pickingServiceBufferCheckCronJob: 4149
    ppsSyncCronJob: 0ede
    printingAdapter: 82bf
    prodProjService: debf
    productAdapter: 5cef
    reportsService: 072e
    systemTests: 5fe3
    tokenExchangeService: eaa2
    webhookDeliveryService: aa9a
    webhookDeliveryServiceCronJob: e9b4