apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: {{ .Values.clientValues.clientName }}-{{ .Values.environmentConfig.envName }}-{{ .Values.environmentConfig.keyVaulName }}
spec:
  provider: azure
  secretObjects:
  {{- range .Values.k8s_secrets }}
  - secretName: {{ .k8s_secret_name }}
    type: {{ .k8s_secret_type }}
    {{- if .k8s_secret_label }}
    labels:
      {{ .k8s_secret_label}}
    {{- end }}
    data:
      {{- range .data }}
      - key: {{ .k8s_secret_key }}
        objectName: {{ .kv_secret_name }}
  {{- end }}
  {{- end }}
  parameters:
    objects:  |
      array:
      {{- range .Values.k8s_secrets }}
      {{- range .data }}
        - |
          objectName: {{ .kv_secret_name }}
          objectType: secret
    {{- end }}
    {{- end }}
    keyvaultName: "{{ .Values.environmentConfig.keyVaulName }}"
    tenantID: "{{ .Values.globalValues.tenantId }}"
    clientID: "{{ .Values.environmentConfig.managedIdClientId }}"
    resourceGroup: "{{ .Values.environmentConfig.resourceGroup }}"
    subscriptionId: "{{ .Values.environmentConfig.subscriptionId }}"