---
apiVersion: v1
data:
  type: {{ .Values.repositoryType | b64enc  }}
  url: {{ .Values.repositoryURL | b64enc }}
kind: Secret
metadata:
  annotations:
    managed-by: argocd.argoproj.io
  labels:
    argocd.argoproj.io/secret-type: repository
  name: {{ .Values.repositoryName }}
  namespace: {{ .Values.namespace }}
type: Opaque
