{{- range .Values.RunnerDeployment }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .name }}
  namespace: {{ .namespace }}  
data:
{{- range $key, $value := .configMap }}
  {{ $key }}: {{ $value | quote }}
{{- end }}
---
{{- end }}
