{{- range .Values.RunnerDeployment }}
apiVersion: actions.summerwind.dev/v1alpha1
kind: RunnerDeployment
metadata:
  name: {{ .name }}
  namespace: {{ .namespace }}
spec:
  template:
    spec:
      image: {{ .image }}
      labels:
        {{- range .runnerLabel }}
        - {{ . }}
        {{- end }}
      organization: TDS
      envFrom:
        - configMapRef:
            name: {{ .name }}
      env:
        {{- range .secrets }}
        - name: {{ .name }}
          valueFrom:
            secretKeyRef:
              name: {{ .secretKeyRef_name }}
              key: {{ .secretKeyRef_key }}
        {{- end }}          
    {{- with .resources }}
      resources:
{{ toYaml . | indent 8 }}
    {{- end }}        
    {{- with .nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
---
{{- end }}