configMap:
  allowLists:
    getAmendSubGroupV1: "{{ .Values.environmentConfig.clients.gravity }}"
    getPickerDetailsV2: "{{ .Values.environmentConfig.clients.gravity }}"
    postAmendSubGroupV1: "{{ .Values.environmentConfig.clients.gravity }}"
    getColleaguePerformanceV1: "{{ .Values.environmentConfig.clients.gravity }}"
    getDailyStatsV2: "{{ .Values.environmentConfig.clients.gravity }},{{ .Values.environmentConfig.clients.clientCredentialsService }},{{ .Values.environmentConfig.clients.systemTests }}"
    printRoutineProductReportsV1: "{{ .Values.environmentConfig.clients.gravity }}"
    getProgressPanelDetailsV1: "{{ .Values.environmentConfig.clients.gravity }},{{ .Values.environmentConfig.clients.clientCredentialsService }},{{ .Values.environmentConfig.clients.systemTests }}"
    getProductsV1: "{{ .Values.environmentConfig.clients.gravity }}, {{ .Values.environmentConfig.clients.systemTests }}"
    getPrePickProductsV1: "{{ .Values.environmentConfig.clients.gravity }}"
    getSecureOrderLineProductsV1: "{{ .Values.environmentConfig.clients.gravity }}"
    getReportProductsDeltaV1: "{{ .Values.environmentConfig.clients.gravity }}"
    printFestiveFoodLabelV1: "{{ .Values.environmentConfig.clients.gravity }}"
    getPrePickLastPrintedV1: "{{ .Values.environmentConfig.clients.gravity }}"
    postPrePickLastPrintedV1: "{{ .Values.environmentConfig.clients.gravity }}"
    pickStartNotificationV1: "{{ .Values.environmentConfig.clients.gravity }}"
    getAllOrdersV2: "{{ .Values.environmentConfig.clients.gravity }},{{ .Values.environmentConfig.clients.systemTests }},{{ .Values.environmentConfig.clients.clientCredentialsService }}"
    getTrayChangesV1: "{{ .Values.environmentConfig.clients.gravity }}"
    getItemRemovalsV1: "{{ .Values.environmentConfig.clients.gravity }}"
    getOrderDetailsV1: "{{ .Values.environmentConfig.clients.gravity }},{{ .Values.environmentConfig.clients.systemTests }}"
    printLabelsV1: "{{ .Values.environmentConfig.clients.gravity }}"
    makeTrayChangesAsCompleteV1: "{{ .Values.environmentConfig.clients.gravity }}"
    exportOrdersV1: "{{ .Values.environmentConfig.clients.gravity }}"
    exportUnmannedOrdersV1: "{{ .Values.environmentConfig.clients.gravity }}"
    markItemRemovalAsCompleteV1: "{{ .Values.environmentConfig.clients.gravity }}"
  otel:
    otelInstrumentationCommonDefaultEnabled: "true"
