apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: {{ .Values.clientValues.clientName }}-{{ .Values.environmentConfig.envName }}-clusterissuer
spec:
  acme:
    server: {{ .Values.server}}
    email: {{ .Values.email }}
    privateKeySecretRef:
      name: {{ .Values.clientValues.clientName }}-{{ .Values.environmentConfig.envName }}-clusterissuer
    solvers:
    - dns01:
        azureDNS:
          subscriptionID: {{ .Values.environmentConfig.subscriptionId }}
          resourceGroupName: {{ .Values.environmentConfig.resourceGroup }}
          hostedZoneName: {{ .Values.hostedZoneName }}
          environment: {{ .Values.DnsEnvironment }}
          managedIdentity:
            clientID: {{ .Values.environmentConfig.managedIdClientId }}
