RunnerDeployment:
  - name: default

    image: "summerwind/actions-runner:v2.316.1-ubuntu-20.04-a6d87c4"

    namespace: "actions-runner-system"

    minNumberOfRunners: 10
    maxNumberOfRunners: 200

    runnerLabel:
      - self-hosted

    configMap:
      GH_HOST: github.dev.global.tesco.org
      ACR: euwdev304sepacr.azurecr.io

    secrets:
      - name: dummy_name
        secretKeyRef_name: dummy_secret_name
        secretKeyRef_key: dummy_secret_keys

    resources:
      requests:
        memory: "2Gi"
        cpu: "1"
    #  limits:
    #    memory: "6Gi"
    #    cpu: "6"

    nodeSelector:
      component: ghrun
    affinity: {}
    tolerations: {}