defaults:
  argo:
    syncPolicy:
      syncOptions:
        - CreateNamespace=true
        - ApplyOutOfSyncOnly=true
        - ServerSideApply=true

cluster:
  name: aks-dev-northeurope-sndbx

metrics:
  enabled: true
  cost:
    enabled: false
  node-exporter:
    enabled: true
logs:
  enabled: true
  pod_logs:
    enabled: true
  cluster_events:
    enabled: true
traces:
  enabled: true
receivers:
  grpc:
    enabled: true
  http:
    enabled: true
  zipkin:
    enabled: false
  grafanaCloudMetrics:
    enabled: true
opencost:
  enabled: false
kube-state-metrics:
  enabled: true
prometheus-node-exporter:
  enabled: true
prometheus-operator-crds:
  enabled: false
alloy: {}
alloy-events: {}
alloy-logs: {}

externalServices:
  prometheus:
    hostKey: host
    basicAuth:
      usernameKey: username
      passwordKey: password
    secret:
      create: false
      name: "prometheus-scraping"
      namespace: "apps"
  loki:
    hostKey: host
    basicAuth:
      usernameKey: username
      passwordKey: password
    secret:
      create: false
      name: "loki-scraping"
      namespace: "apps"
  tempo:
    hostKey: host
    basicAuth:
      usernameKey: username
      passwordKey: password
    secret:
      create: false
      name: "tempo-scraping"
      namespace: "apps"
