name: Call system test at Trn-Stg environment
on:
  workflow_dispatch:
  schedule:
    - cron: "0 5 * * *"

jobs:
  call-system-tests:
    uses: TDS/tds-automation/.github/workflows/call-system-tests.yml@main
    with:
      config_file: "listen-dispatch-event-staging.yml"
