name: Environment promotion
run-name: Promote ${{ inputs.tenant_from || 'trn' }}-${{ inputs.env_from || 'dev' }} environment to ${{ inputs.tenant_to || 'trn' }}-${{ inputs.env_to || 'stg' }} environment
on:
  repository_dispatch:
    types: [PROMOTION]
    branches:
      - main
  workflow_dispatch:
    inputs:
      tenant_from:
        description: Tenant with newest applications version
        type: choice
        default: "trn"
        options:
          - "trn"
          - sndbx
          - fs
      env_from:
        description: Environment
        type: choice
        default: dev
        options:
          - dev
          - stg
          - prod
      tenant_to:
        description: Tenant where new versions should be installed
        type: choice
        default: "fs"
        options:
          - "trn"
          - sndbx
          - fs
      env_to:
        description: Environment
        type: choice
        default: prod
        options:
          - dev
          - stg
          - prod

jobs:
  promote-environment:
    concurrency: environment-promotion-${{ github.ref }}
    uses: TDS/tds-automation/.github/workflows/promote-environment.yml@main
    with:
      tenant_from: ${{ inputs.tenant_from || 'trn' }}
      env_from: ${{ inputs.env_from || 'dev' }}
      tenant_to: ${{ inputs.tenant_to || 'trn' }}
      env_to: ${{ inputs.env_to || 'stg' }}
    secrets: inherit
