name: Promote Trn-Stg to Trn-Prod and tag release
on:
  workflow_dispatch:
jobs:
  call-system-tests:
    uses: TDS/tds-automation/.github/workflows/call-system-tests.yml@main
    with:
      config_file: 'listen-dispatch-event-staging.yml'
  create-release:
    needs: call-system-tests
    uses: TDS/tds-automation/.github/workflows/create-release.yml@main
  promote-stg-to-prod:
    concurrency: promotion-stg-to-prod-${{ github.ref }}
    needs: create-release
    uses: TDS/tds-automation/.github/workflows/promote-environment.yml@main
    with:
      tenant_from: 'trn'
      env_from: 'stg'
      tenant_to: 'trn'
      env_to: 'prod'
    secrets: inherit
